ALTER TABLE group_posts
    ADD COLUMN IF NOT EXISTS trail_id BIGINT REFERENCES story_trails(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_group_posts_trail_created ON group_posts(trail_id, created_at DESC);

CREATE TABLE IF NOT EXISTS group_post_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_post_id BIGINT NOT NULL REFERENCES group_posts(id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES group_post_comments(id) ON DELETE CASCADE,
    body VARCHAR(5000) NOT NULL,
    flagged BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_group_post_comments_post_created ON group_post_comments(group_post_id, created_at);
CREATE INDEX IF NOT EXISTS idx_group_post_comments_parent ON group_post_comments(parent_id);
