ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;

UPDATE users
    SET email_verified = FALSE
    WHERE email_verified IS NULL;

ALTER TABLE IF EXISTS users
    ALTER COLUMN email_verified SET NOT NULL;

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS verification_token VARCHAR(255);

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS password_reset_token VARCHAR(255);

ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS password_reset_expires_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE IF EXISTS news_headlines
    ALTER COLUMN title TYPE TEXT,
    ALTER COLUMN source_url TYPE TEXT,
    ALTER COLUMN source_name TYPE TEXT,
    ALTER COLUMN image_url TYPE TEXT;

ALTER TABLE IF EXISTS news_headlines
    ADD COLUMN IF NOT EXISTS description TEXT;

CREATE TABLE IF NOT EXISTS story_trails (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    slug VARCHAR(180) NOT NULL UNIQUE,
    description VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE IF EXISTS posts
    ADD COLUMN IF NOT EXISTS trail_id BIGINT;

ALTER TABLE IF EXISTS posts
    ADD COLUMN IF NOT EXISTS source_url VARCHAR(2048);

CREATE INDEX IF NOT EXISTS idx_posts_trail_id ON posts(trail_id);

CREATE TABLE IF NOT EXISTS reader_pulses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    choice VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_reader_pulses_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reader_pulses_post_id ON reader_pulses(post_id);

CREATE TABLE IF NOT EXISTS group_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES community_groups(id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(140) NOT NULL,
    body VARCHAR(5000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_group_posts_group_created ON group_posts(group_id, created_at DESC);

ALTER TABLE IF EXISTS group_posts
    ADD COLUMN IF NOT EXISTS trail_id BIGINT REFERENCES story_trails(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_group_posts_trail_created ON group_posts(trail_id, created_at DESC);

CREATE TABLE IF NOT EXISTS group_post_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_post_id BIGINT NOT NULL REFERENCES group_posts(id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES group_post_comments(id) ON DELETE CASCADE,
    body VARCHAR(5000) NOT NULL,
    flagged BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_group_post_comments_post_created ON group_post_comments(group_post_id, created_at);
CREATE INDEX IF NOT EXISTS idx_group_post_comments_parent ON group_post_comments(parent_id);

CREATE TABLE IF NOT EXISTS friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_friendships_requester_recipient UNIQUE (requester_id, recipient_id),
    CONSTRAINT ck_friendships_distinct_users CHECK (requester_id <> recipient_id)
);

CREATE INDEX IF NOT EXISTS idx_friendships_recipient_status ON friendships(recipient_id, status);
CREATE INDEX IF NOT EXISTS idx_friendships_requester_status ON friendships(requester_id, status);

ALTER TABLE IF EXISTS community_groups
    ADD COLUMN IF NOT EXISTS visibility VARCHAR(16) NOT NULL DEFAULT 'PUBLIC',
    ADD COLUMN IF NOT EXISTS join_policy VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    ADD COLUMN IF NOT EXISTS topics VARCHAR(500),
    ADD COLUMN IF NOT EXISTS rules VARCHAR(2000);

CREATE TABLE IF NOT EXISTS group_join_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL REFERENCES community_groups(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_group_join_requests_group_user UNIQUE (group_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_group_join_requests_group_status
    ON group_join_requests(group_id, status);
